Link results to questionnaire
mcode/abstraction-tool pull request #15
Opened 2020-09-10 19:27 UTC by mickohanlon23

**Build out `results-processing.ts`:**
1. Extracts out FHIR Objects from the ELM execution
2. Links FHIR Objects to matching item IDs from the Questionnaire
3. Creates an answerOption for each matched resource, which is displayed on the questionnaire

To test:
- Questionnaire should display [object Object] as value for CancerRelatedSurgicalProcedure and TumorMarker (in the future we should look into modifying Lform to display what we want)
- The console should log the updated Questionnaire resource, which should include answerOption fields for CancerRelatedSurgicalProcedure and TumorMarker.

2020-09-14 18:58 UTC, mickohanlon23 commented on src/utils/results-processing.ts
> +      valueReference: {
If you want to see the actual reference populated into the questionnaire, change this to 
`  const referenceObject = {
      valueReference: referenceLocation
    };`
It shows `[object Object]` the way the code is written now because the lforms widget does not seem to have full support for `valueReference` as and answerOption. I'm open to talking about what we actually want this reference object to look like.

2020-09-15 19:38 UTC, mgramigna requested changes

2020-09-15 19:38 UTC, mgramigna commented on src/utils/results-processing.ts
> +  function createAnswerOption(fhirObject: any) {
Can you pull this function out to its own scope

2020-09-15 19:38 UTC, mgramigna commented on src/utils/results-processing.ts
> +    let referenceLocation = fhirObject._json.resourceType + '/' + fhirObject.id.value;
```suggestion
    const referenceLocation = `${fhirObject._json.resourceType}/${fhirObject.id.value}`;
```

2020-09-15 19:38 UTC, mgramigna commented on src/utils/results-processing.ts
> +export default function questionnaireUpdater(cqlResults: any, questionnaire: R4.IQuestionnaire): R4.IQuestionnaire {
Maybe we can update the arguments of this to take a patient Id string in as an argument. That way, we can pull the patient ID off of the patient data bundle in the Abstractor and pass it in, rather than accessing the first entry on the patientResults object like you do below.

2020-09-15 19:38 UTC, mgramigna commented on src/utils/results-processing.ts
> +  }
I think this block of code can be simplified to not need a triple for. In english, the algorithm could be as follows:

1. Iterate through every entry on the patientResults data
2. if the resource List is non-empty, do a `.find` on `questionnaire.item`. 
3. answerOption should be an array, for each result in the resource list, map it to an answer option (can use `.map` here).
4. Push the result onto a new array local variable for the updated questionnaire.item
5. At the end of everything, set `questionnaire.item` to the new value as you currently do.

This was a little stream of consciousness, but I think it will improve efficiency and readability.

2020-09-23 17:54 UTC, mgramigna requested changes

2020-09-23 17:54 UTC, mgramigna commented on src/utils/results-processing.ts
> +  let questionnaireItems: any = questionnaire.item;
this should not have `any` type. It will infer the type from the R4 Interface for questionnaire

2020-09-23 17:54 UTC, mgramigna commented on src/utils/results-processing.ts
> +function createAnswerOption(fhirObject: any) {
This function should have a return type of `R4.IQuestionnaire_AnswerOption`

2020-09-23 17:54 UTC, mgramigna commented on src/utils/results-processing.ts
> +        );
```suggestion
        matchingResource.answerOption = matchingResource.answerOption.concat(newAnswerOptions);
```

2020-09-23 17:54 UTC, mgramigna commented on src/utils/results-processing.ts
> +      if (!matchingResource.answerOption) {
Sometimes JS can be weird here. I'd add a more robust check:

```suggestion
      if (matchingResource.answerOption === undefined || matchingResource.answerOption.length === 0) {
```

2020-09-23 17:54 UTC, mgramigna commented on src/utils/results-processing.ts
> +      const matchingResource = questionnaireItems.find((element: any) => element.linkId === key);
```suggestion
      const matchingResource = questionnaireItems.find(element => element.linkId === key);
```
You should be able to drop the `any` type from this if you drop the any from the questionnaireItems variable above

2020-09-23 17:54 UTC, mgramigna commented on src/utils/results-processing.ts
> +  let questionnaireItems: any = questionnaire.item;
this might make you add some if guards around some code blocks. this is fine

2020-09-23 17:54 UTC, mgramigna commented on src/utils/results-processing.ts
> +  questionnaire.item = questionnaireItems;
```suggestion
```
If you're modifying the entry in the original array like you're doing above with the index, then you shouldn't actually need this line. It should still work.

2020-09-24 14:34 UTC, mgramigna approved these changes

2020-09-24 14:34 UTC, merged