Questionnaire response rebased
mcode/abstraction-tool pull request #18
Opened 2020-10-01 14:05 UTC by mickohanlon23

Review this one, since the other pull request didn't have an updated version of master.

2020-10-01 15:14 UTC, pmadria commented on src/components/Abstractor/Abstractor.tsx
> +      console.log(lform);
```suggestion

```

2020-10-01 15:14 UTC, pmadria commented on src/components/Abstractor/Abstractor.tsx
> +      //window.LForms.Util.mergeFHIRDataIntoLForms("QuestionnaireResponse", qr, lform, "R4");
```suggestion

```

2020-10-01 15:36 UTC, mickohanlon23 commented on src/components/Abstractor/Abstractor.tsx
> +      //window.LForms.Util.mergeFHIRDataIntoLForms("QuestionnaireResponse", qr, lform, "R4");
I think logging the questionnaire response is good for now since it shows that the functionality actually works, but agree that we should delete it at some future point.

2020-10-02 14:41 UTC, mgramigna requested changes
Line 10 on App.tsx still has a commented out import. Remove that and i’ll merge

2020-10-02 16:23 UTC, mgramigna approved these changes

2020-10-02 16:23 UTC, merged