removed script tags and now adding via require statement
mcode/abstraction-tool pull request #24
Opened 2020-10-28 15:36 UTC by pmadria

This is for task 55. The script tags were removed and instead is being inserted via a require statement. The issue for the unit test (SyntaxError: Cannot use import statement outside a module) is still occurring and will be updated accordingly after some feedback.

2020-11-10 21:36 UTC, mickohanlon23 requested changes
I think we actually might be able to delete all of the other lforms files except for the three minified files that are called within `index.html`, since I don't think we would ever be rebuilding the minified within public/static. I believe if we make future changes to lforms, we would just want to manually re-upload the modified minified files. I just tried running after deleting all of the added lforms files except for `./static/lforms/lforms-26.2.0/styles/lforms.min.css`, `./static/lforms/lforms-26.2.0/lforms.min.js`, and `./static/lforms/lforms-26.2.0/fhir/lformsFHIRAll.min.js` and everything still works as expected. I would double check with @mgramigna about this.

We also probably want to modify the part in the README about adding the lforms references to index.html to reflect how we now refer to the minified lforms code from within our own project.

2020-11-10 21:36 UTC, mickohanlon23 commented on package.json
> +    "lforms": "^26.3.1",
```suggestion
```
We probably don't still want to import `lforms` as a dependency, since we're now referring to the version of lforms that you put within `public/static`

2020-11-10 21:36 UTC, mickohanlon23 commented on yarn.lock
> +"@lhncbc/ucum-lhc@^4.1.3":
We should run yarn install after removing the lforms dependency in package.json, since we're now calling our own local version of lforms

2020-11-10 21:36 UTC, mickohanlon23 commented on public/index.html
> +    <link href="./static/dist/lforms-26.2.0/styles/lforms.min.css" media="screen" rel="stylesheet" />
```suggestion
    <link href="./static/lforms/lforms-26.2.0/styles/lforms.min.css" media="screen" rel="stylesheet" />
```
This folder should be called `lforms` since you changed the name from `dist/` to `lforms/` within our `public/static` folder.

2020-11-10 21:36 UTC, mickohanlon23 commented on public/index.html
> +    <script crossorigin="anonymous" src="./static/dist/lforms-26.2.0/fhir/lformsFHIRAll.min.js"></script>
```suggestion
    <script crossorigin="anonymous" src="./static/lforms/lforms-26.2.0/lforms.min.js"></script>
    <script crossorigin="anonymous" src="./static/lforms/lforms-26.2.0/fhir/lformsFHIRAll.min.js"></script>
```
Same change as above

2020-11-10 22:05 UTC, pmadria commented
> I think we actually might be able to delete all of the other lforms files except for the three minified files that are called within `index.html`, since I don't think we would ever be rebuilding the minified within public/static. I believe if we make future changes to lforms, we would just want to manually re-upload the modified minified files. I just tried running after deleting all of the added lforms files except for `./static/lforms/lforms-26.2.0/styles/lforms.min.css`, `./static/lforms/lforms-26.2.0/lforms.min.js`, and `./static/lforms/lforms-26.2.0/fhir/lformsFHIRAll.min.js` and everything still works as expected. I would double check with @mgramigna about this.
> 
> We also probably want to modify the part in the README about adding the lforms references to index.html to reflect how we now refer to the minified lforms code from within our own project.

Yep I agree. I left them in there so Matt could take a look at them just in case we might need them in the future but agreed it did work without all those minus those files you mentioned.

2020-11-12 15:21 UTC, pmadria commented on yarn.lock
> +"@lhncbc/ucum-lhc@^4.1.3":
done!

2020-11-12 15:26 UTC, mgramigna requested changes
Can we only include the files in public/static that we need? i.e. the two js files and the css file that you're referencing. Otherwise we should keep it clean and not include anything else

2020-11-12 15:45 UTC, pmadria commented
Removed all but the three files we need

2020-11-12 15:47 UTC, mgramigna approved these changes

2020-11-12 16:22 UTC, mickohanlon23 approved these changes
Looks good!

2020-11-12 18:11 UTC, merged