Add support for any type supported in answer option
mcode/abstraction-tool pull request #27
Opened 2020-11-10 23:24 UTC by mgramigna

2020-11-11 19:39 UTC, mickohanlon23 reviewed
This looks awesome, great job with the tests. I'm not sure if my comments will directly require changes, but I primarily just wanted to clarify a few different things.

2020-11-11 19:39 UTC, mickohanlon23 commented on src/utils/results-processing.ts
> +  if (R4.RTTI_Coding.decode(cqlResult._json).isRight()) {
Shouldn't we be checking for `RTTI_CodeableConcept` here? In the `createValueCodingAnswerOption` function, it looks like we want to find the `coding` property of cqlResult, but according to https://github.com/Ahryman40k/typescript-fhir-types/blob/4.0.0/src/R4/Resource/RTTI_Coding.ts, if the type check for `RTTI_Coding` returned true, cqlResults wouldn't then have a .coding property.

2020-11-11 19:39 UTC, mickohanlon23 commented on src/utils/results-processing.ts
> +  if (R4.RTTI_Coding.decode(cqlResult._json).isRight()) {
Should we have support both for an answer coming in as a Coding data type and as a CodeableConcept data type, since CQL could return either?

2020-11-11 19:39 UTC, mickohanlon23 commented on src/utils/results-processing.ts
> +    return createPrimitiveAnswerOption('valueTime', (cqlResult as Date).toString());
Where do the isDate and isDateTime properties come from? Is this a special way that dates come back from the CQL engine? Is there a reason not to use RTTI_date and RTTI_dateTime?

2020-11-12 04:11 UTC, pmadria commented
Took a look at the PR...nothing stands out different than what Mick has pointed out

2020-11-12 15:55 UTC, mgramigna commented on .eslintrc.json
> -{
Sorry yeah I deleted the eslint files because our lint is now pre-loaded with create-react-app so these files actually don't do anything

2020-11-12 16:08 UTC, mgramigna commented on src/utils/results-processing.ts
> +    return createPrimitiveAnswerOption('valueTime', (cqlResult as Date).toString());
Yeah so these are properties that are set by the CQL engine. figured it made sense to use them seeing as they come back directly from the engine rather than use the run time type checking.

In addition, the javascript `Date` object is native to javascript so it comes back from the JS cql engine as a date object already, when these flags are set. So I don't see a need for using RTTI since we have all the info we need in JS

2020-11-12 19:29 UTC, mgramigna commented on src/utils/results-processing.ts
> +  if (R4.RTTI_Coding.decode(cqlResult._json).isRight()) {
You're right, good catch.

2020-11-12 19:52 UTC, mgramigna commented on src/utils/results-processing.ts
> +  if (R4.RTTI_Coding.decode(cqlResult._json).isRight()) {
I just pushed up something for this. It was a little tough. It assumes that a coding comes back as an array since that how it looks in FHIR. 

Also, for some reason, full FHIR resources were passing the RTTI check for Coding, so I moved the valueReference handling as the first case to work around that.

2020-11-13 15:54 UTC, mickohanlon23 commented on src/utils/results-processing.ts
> +  if (R4.RTTI_Coding.decode(cqlResult._json).isRight()) {
Yeah, I think because a CodeableConcept can technically contain a list of Codings. I think it's fair for us to just assume that we want to just index the first coding in the array, unless for some reason we wanted to add an array of multiple codings as multiple answer options, but I don't necessarily see a reason why that would be useful.

2020-11-13 16:24 UTC, mgramigna commented on src/utils/results-processing.ts
> +  if (R4.RTTI_Coding.decode(cqlResult._json).isRight()) {
Yeah agreed, I'm gonna mark this as resolved then

2020-11-13 16:45 UTC, mickohanlon23 requested changes
Looks great! Both Coding and CodeableConcept are covered by the tests now which is good. Tested with example-datatypes-questionnaire.json and answer options seem to be adding to the questionnaire just as we want them to. I think the only immediate change is to rebase to account for the new results-processing functionality merged in yesterday.

2020-11-13 16:45 UTC, mickohanlon23 commented on src/utils/results-processing.ts
>          const matchingResource = questionnaireItems.find(element => element.linkId === key) as R4.IQuestionnaire_Item;
Assuming we'll need a rebase due to yesterday's merged change to how we query the expression name here.

2020-11-13 16:45 UTC, mickohanlon23 commented on src/utils/results-processing.ts
> +function createValueCodingAnswerOptionCoding(cqlResult: R4.ICoding): R4.IQuestionnaire_AnswerOption {
One thing I noticed while testing (with your example-datatypes-questionnaire.json file) is that the QuestionnaireResponse is storing every new type of answerOption you implemented as a valueCoding. I believe this is because LForms assumes that questionnaire items of type choice are valueCoding types. Probably something that should be fixed, but I think that would probably be out of the scope of this task.

2020-11-18 17:37 UTC, mgramigna commented
@mickohanlon23 Fingers crossed the primitives should be handled now

2020-11-24 15:15 UTC, mickohanlon23 commented on src/utils/results-processing.ts
> +      key === Primitives.DATE || key === Primitives.DATETIME || key === Primitives.TIME
This line is giving me the following error for the 3rd conditional: 

> This condition will always return 'false' since the types '"valueInteger" | "valueString"' and 'Primitives.DATETIME' have no overlap.

Could we just check if key is equal to the strings 'valueDate' or 'valueTime'?

2020-11-24 15:24 UTC, mickohanlon23 reviewed
I made one more comment about an error I was getting when running in VSCode.

Other than that, the only issue I see is that I am getting console warnings relating to an lforms font that is unable to be downloaded when I run the tool using the example-datatypes-questionnaire. The button allowing to choose a date from a calendar is mostly off the screen as well, so I believe the warning has to do with that. This isn't really relevant to this task, so I don't see this as an actual issue right now.

2020-11-24 18:05 UTC, mgramigna commented on src/utils/results-processing.ts
> +      key === Primitives.DATE || key === Primitives.DATETIME || key === Primitives.TIME
done

2020-11-24 18:38 UTC, mickohanlon23 approved these changes

2020-11-30 15:45 UTC, merged