Modal for QR and HL7 message
mcode/abstraction-tool pull request #29
Opened 2020-11-24 19:59 UTC by pmadria

Added modal functionality to generation of QR response and HL7 message. Can look to polish further if necessary. 

Note: "Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode." Functionality works as intended but not sure if this needs to be addressed or not.

2020-11-25 16:44 UTC, mickohanlon23 requested changes
![Screen Shot 2020-11-25 at 11 42 50 AM](https://user-images.githubusercontent.com/51176978/100256957-5f9de700-2f13-11eb-88b1-008e78ecc69a.png)
I'm getting this warning in the console when I click either of the buttons. Not sure how important it is - is this something we should fix?

2020-11-25 16:44 UTC, mickohanlon23 commented on src/components/ExportDialog/ExportDialog.tsx
> +import React, { useEffect, useState } from 'react';
```suggestion
import React from 'react';
```
These were unused. Removing them will get rid of Typescript error.

2020-11-25 16:44 UTC, mickohanlon23 commented on src/components/Abstractor/Abstractor.tsx
>  export interface Props {
```suggestion
import ExportDialog from '../ExportDialog/ExportDialog';

export interface Props {
```

2020-11-25 16:44 UTC, mickohanlon23 commented on src/components/Abstractor/Abstractor.tsx
> +    let response = ''
```suggestion
    let response = '';
```

2020-11-25 16:44 UTC, mickohanlon23 commented on src/components/Abstractor/Abstractor.tsx
> +    setModalContent(response)
```suggestion
    setModalContent(response);
```

2020-11-25 16:44 UTC, mickohanlon23 commented on src/components/Abstractor/Abstractor.tsx
> +    return JSON.stringify(qr, null, 10)
Do you want to come up with a way to keep the line-breaks in the string version of the questionnaire response so that it is a bit more human-readable?

2020-11-30 15:38 UTC, mgramigna requested changes

2020-11-30 15:38 UTC, mgramigna commented on src/components/ExportDialog/ExportDialog.tsx
> +        </Typography>
Good way to display this would be to surround the content in a `pre` and `code` tag, and delete the Typography.

Should look like this:

``` jsx
<pre>
  <code>
    {content}
  </code>
</pre>
```

2020-11-30 15:38 UTC, mgramigna commented on src/components/Abstractor/Abstractor.tsx
> +    return myEscapedJSONString;
these replaces shouldn't be necessary... the stringify with null and 2 should space things out properly, and using `<pre>` and `<code>` like I mentioned should take care of the display.

```suggestion
    return JSON.stringify(exporter, null, 2);
```

2020-11-30 15:38 UTC, mgramigna commented on src/components/ExportDialog/ExportDialog.tsx
> +import React, { useEffect, useState } from 'react';
Can you add an `index.ts` file to this folder similar to how we do to other components?

2020-11-30 16:12 UTC, mgramigna commented
> ![Screen Shot 2020-11-25 at 11 42 50 AM](https://user-images.githubusercontent.com/51176978/100256957-5f9de700-2f13-11eb-88b1-008e78ecc69a.png)
> I'm getting this warning in the console when I click either of the buttons. Not sure how important it is - is this something we should fix?

I believe this is a problem with material ui. At least according to multiple github threads. We can ignore this for now.

2020-11-30 16:26 UTC, pmadria commented on src/components/ExportDialog/ExportDialog.tsx
> +import React, { useEffect, useState } from 'react';
yep done!

2020-11-30 21:17 UTC, mgramigna approved these changes

2020-12-01 06:30 UTC, mickohanlon23 approved these changes
QR Response looks great!

2020-12-01 14:16 UTC, merged